### ISSUE TITLE
Unicauca Version2 Dataset

### ISSUE THREAD

**Issue by zgzhengSEU** [indrapaul824/5G-Network-Slicing#4]
Hi, brother, you did a great job! I wonder where can I get unicauca version 2 dataset? Can you give me a link? Thank you very much!

**Comment by IndraP24** [comment]
Hey, thanks for the review! I collected the data from Kaggle. You can find it here: ([dataset link](https://www.kaggle.com/jsrojas/ip-network-traffic-flows-labeled-with-87-apps)).
